stages:
  load_data:
    cmd: python src/data_load.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/data_load.py
    - dataFromSrc/winequality.csv
    outs:
    - data/raw/winequality.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv